
name: dsc180A
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7
    - numpy=1.16.4
    - tensorflow
    - scikit-learn
    - matplotlib
    - tqdm
    - pip
    - jupyter
    - pip:
      - pandas
